version: '3.8'

services:
  ypes-mirror:
    build: .
    container_name: ypes-mirror-app
    ports:
      - "81:1"
    environment:
      - PORT=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
